#!/bin/bash

# Dirs
export CONFIG_DIR="$HOME/.config/sketchybar"
export PLUGIN_DIR="$CONFIG_DIR/plugins"

# Colours config file
source "$CONFIG_DIR/colors.sh" # Loads defined colours

# === Bar Appearance ===	
sketchybar --bar position=top      \
		 height=33         \
		 blur_radius=4    \
   		 color=0x40000000 \
		 sticky=on


# === Defaults ===

default=(
  # Padding
  padding_left=5
  padding_right=5

  # Icons
  icon.font="SF Pro:Bold:17.0"
  icon.color=$LABEL_COLOR
  icon.padding_left=7
  icon.padding_right=4

  # Labels
  label.font="SF Pro:Bold:14.0"
  label.color=$LABEL_COLOR
  label.font_smoothing=on
  label.padding_left=4
  label.padding_right=4

  # Background
  background.corner_radius=5
  background.color=$ITEM_BG_COLOR
  background.height=30 
  background.border_color=$BORDER_COLOR 
  background.border_width=2 
  background.corner_radius=20 
)
sketchybar --default "${default[@]}"


# == Left Side Items ==


# == Right Side Items == 

# Kill any existing instance of stats_provider, silencing error messages
killall stats_provider 2>/dev/null

# Instantiate stats_provider
$HOME/.local/bin/stats_provider --cpu usage --memory ram_usage --interval 2 &

# CPU
source "$PLUGIN_DIR/cpu.sh"
sketchybar --subscribe cpu system_stats

# RAM
source "$PLUGIN_DIR/ram.sh"
sketchybar --subscribe ram system_stats

# Group the CPU & RAM together using a bracket
sketchybar --add bracket system_stats_right cpu ram \
	   --set system_stats_right background.color=$BG_DARKER \
				    background.corner_radius=20 \
				    background.border_width=0 \
				    background.height=30 

# Battery 
source "$PLUGIN_DIR/battery.sh"

# Calendar
source "$PLUGIN_DIR/calendar.sh"

# Clock
source "$PLUGIN_DIR/clock.sh"

# == Item Order ==
# For some reason they have to be in backwards order (rightmost > leftmost)
sketchybar --reorder clock calendar battery ram cpu 


           #### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
